struct TreeNode
{
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode() : val(0), left(nullptr), right(nullptr) {}
    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
    TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
};

/* 反转二叉树 */

TreeNode *invertTree(TreeNode *root)
{ // 交换两个儿子
    if (root == nullptr)
        return nullptr;
    invertTree(root->left);
    invertTree(root->right);
    TreeNode *tmp = root->left;
    root->left = root->right;
    root->right = tmp;

    return root;
}